// : Generated by xaf-index-generator :

export { default as AppFooter } from './app.footer.vue'
export { default as AppHeader } from './app.header.vue'
export { default as AppNotifications } from './app.notifications.vue'