version: '2'
services:
  backend:
    build: ./backend
    command: bash -c "uvicorn app.asgi:app --host 0.0.0.0 --port 1337"
    ports:
      - "1337:1337"
    volumes:
      - ./backend/.:/code
    tty: true

  frontend:
    build:
      context: ./frontend
    ports:
      - '8000:80'
    volumes:
      - './frontend:/app'
    links:
      - "backend:backend"

  mongodb:
    image: mongo:latest
    restart: always
    expose:
      - 27017
    ports:
      - 27020:27017
    volumes:
      - ./mongo:/data/db
      - ./dump:/opt/dump
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin