// : Generated by xaf-index-generator :

export { default as IconCriticalRound } from './icon.critical-round.vue'
export { default as IconCriticalSquare } from './icon.critical-square.vue'
export { default as IconLogo } from './icon.logo.vue'
export { default as IconOil } from './icon.oil.vue'
export { default as IconOkRound } from './icon.ok-round.vue'
export { default as IconTemperature } from './icon.temperature.vue'
export { default as IconVibration } from './icon.vibration.vue'
export { default as IconWarningSquare } from './icon.warning-square.vue'