// : Generated by xaf-index-generator :

export { default as PageGraph } from './page.graph.vue'
export { default as PageMain } from './page.main.vue'
export { default as PageScheme } from './page.scheme.vue'