export const enums = {
  p1: {
    temp_p1: 'Подшипник 1:temperature',
    vibration_p1: 'Подшипник 1:vibration_axial',
    horizontal_p1: 'Подшипник 1:vibration_horizontal',
    vertical_p1: 'Подшипник 1:vibration_vertical',
  },
  p2: {
    temp_p2: 'Подшипник 2:temperature',
    vibration_p2: 'Подшипник 2:vibration_axial',
    horizontal_p2: 'Подшипник 2:vibration_horizontal',
    vertical_p2: 'Подшипник 2:vibration_vertical',
  },
  p3: {
    temp_p3: 'Подшипник 3:temperature',
    vibration_p3: 'Подшипник 3:vibration_axial',
    horizontal_p3: 'Подшипник 3:vibration_horizontal',
    vertical_p3: 'Подшипник 3:vibration_vertical',
  },
  p4: {
    temp_p4: 'Подшипник 4:temperature',
    vibration_p4: 'Подшипник 4:vibration_axial',
    horizontal_p4: 'Подшипник 4:vibration_horizontal',
    vertical_p4: 'Подшипник 4:vibration_vertical',
  },
  p5: {
    temp_p5: 'Подшипник 5:temperature',
    vibration_p5: 'Подшипник 5:vibration_axial',
    horizontal_p5: 'Подшипник 5:vibration_horizontal',
    vertical_p5: 'Подшипник 5:vibration_vertical',
  },
  p6: {
    temp_p6: 'Подшипник 6:temperature',
    vibration_p6: 'Подшипник 6:vibration_axial',
    horizontal_p6: 'Подшипник 6:vibration_horizontal',
    vertical_p6: 'Подшипник 6:vibration_vertical',
  },
  p7: {
    temp_p7: 'Подшипник 7:temperature',
    vibration_p7: 'Подшипник 7:vibration_axial',
    horizontal_p7: 'Подшипник 7:vibration_horizontal',
    vertical_p7: 'Подшипник 7:vibration_vertical',
  },
  p8: {
    temp_p8: 'Подшипник 8:temperature',
    vibration_p8: 'Подшипник 8:vibration_axial',
    horizontal_p8: 'Подшипник 8:vibration_horizontal',
    vertical_p8: 'Подшипник 8:vibration_vertical',
  },
  p9: {
    temp_p9: 'Подшипник 9:temperature',
    vibration_p9: 'Подшипник 9:vibration_axial',
    horizontal_p9: 'Подшипник 9:vibration_horizontal',
    vertical_p9: 'Подшипник 9:vibration_vertical',
  },
  oil: {
    temp_oil_after: 'Охладитель:temperature_after',
    temp_oil_before: 'Охладитель:temperature_before',
    oil_level: 'Маслосистема:oil_level',
    oil_pressure: 'Маслосистема:oil_pressure',
    work_exgauster: 'SM_Exgauster[0.0]',
  },
  water: {
    temp_water_after: 'SM_Exgauster[0:37]',
    temp_water_before: 'SM_Exgauster[0:36]',
    temp_before_exgauster: 'SM_Exgauster[0:24]',
  },
  gaz: {
    close_gaz: 'SM_Exgauster[1.1]',
    open_gaz: 'SM_Exgauster[1.2]',
    position_gaz: 'SM_Exgauster[1:6]',
  },
  energy: {
    amper_rotor: 'Главный привод:rotor_current',
    volt_rotor: 'Главный привод:rotor_voltage',
    amper_starter: 'Главный привод:stator_current',
    volt_starter: 'Главный привод:stator_voltage',
  },
  underpressure_before: 'SM_Exgauster[0:61]',
};
